package com.witown.dao;

import com.witown.entity.OpenThirdInfo;
import com.witown.entity.OpenThirdInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OpenThirdInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    @SelectProvider(type=OpenThirdInfoSqlProvider.class, method="countByExample")
    int countByExample(OpenThirdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    @DeleteProvider(type=OpenThirdInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(OpenThirdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    @Delete({
        "delete from wi_probe_open_third_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    @Insert({
        "insert into wi_probe_open_third_info (id, appid, ",
        "token, aeskey, url, ",
        "gmtCreated, gmtModified)",
        "values (#{id,jdbcType=INTEGER}, #{appid,jdbcType=VARCHAR}, ",
        "#{token,jdbcType=VARCHAR}, #{aeskey,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, ",
        "#{gmtcreated,jdbcType=TIMESTAMP}, #{gmtmodified,jdbcType=TIMESTAMP})"
    })
    int insert(OpenThirdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    @InsertProvider(type=OpenThirdInfoSqlProvider.class, method="insertSelective")
    int insertSelective(OpenThirdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    @SelectProvider(type=OpenThirdInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="appid", property="appid", jdbcType=JdbcType.VARCHAR),
        @Result(column="token", property="token", jdbcType=JdbcType.VARCHAR),
        @Result(column="aeskey", property="aeskey", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmtCreated", property="gmtcreated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmtModified", property="gmtmodified", jdbcType=JdbcType.TIMESTAMP)
    })
    List<OpenThirdInfo> selectByExample(OpenThirdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    @Select({
        "select",
        "id, appid, token, aeskey, url, gmtCreated, gmtModified",
        "from wi_probe_open_third_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="appid", property="appid", jdbcType=JdbcType.VARCHAR),
        @Result(column="token", property="token", jdbcType=JdbcType.VARCHAR),
        @Result(column="aeskey", property="aeskey", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmtCreated", property="gmtcreated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmtModified", property="gmtmodified", jdbcType=JdbcType.TIMESTAMP)
    })
    OpenThirdInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    @UpdateProvider(type=OpenThirdInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OpenThirdInfo record, @Param("example") OpenThirdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    @UpdateProvider(type=OpenThirdInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OpenThirdInfo record, @Param("example") OpenThirdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    @UpdateProvider(type=OpenThirdInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OpenThirdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    @Update({
        "update wi_probe_open_third_info",
        "set appid = #{appid,jdbcType=VARCHAR},",
          "token = #{token,jdbcType=VARCHAR},",
          "aeskey = #{aeskey,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "gmtCreated = #{gmtcreated,jdbcType=TIMESTAMP},",
          "gmtModified = #{gmtmodified,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OpenThirdInfo record);
}