package com.witown.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.witown.entity.OpenThirdInfo;
import com.witown.entity.OpenThirdInfoExample.Criteria;
import com.witown.entity.OpenThirdInfoExample.Criterion;
import com.witown.entity.OpenThirdInfoExample;
import java.util.List;
import java.util.Map;

public class OpenThirdInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public String countByExample(OpenThirdInfoExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("wi_probe_open_third_info");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public String deleteByExample(OpenThirdInfoExample example) {
        BEGIN();
        DELETE_FROM("wi_probe_open_third_info");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public String insertSelective(OpenThirdInfo record) {
        BEGIN();
        INSERT_INTO("wi_probe_open_third_info");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getAppid() != null) {
            VALUES("appid", "#{appid,jdbcType=VARCHAR}");
        }
        
        if (record.getToken() != null) {
            VALUES("token", "#{token,jdbcType=VARCHAR}");
        }
        
        if (record.getAeskey() != null) {
            VALUES("aeskey", "#{aeskey,jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            VALUES("url", "#{url,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtcreated() != null) {
            VALUES("gmtCreated", "#{gmtcreated,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtmodified() != null) {
            VALUES("gmtModified", "#{gmtmodified,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public String selectByExample(OpenThirdInfoExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("appid");
        SELECT("token");
        SELECT("aeskey");
        SELECT("url");
        SELECT("gmtCreated");
        SELECT("gmtModified");
        FROM("wi_probe_open_third_info");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        OpenThirdInfo record = (OpenThirdInfo) parameter.get("record");
        OpenThirdInfoExample example = (OpenThirdInfoExample) parameter.get("example");
        
        BEGIN();
        UPDATE("wi_probe_open_third_info");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getAppid() != null) {
            SET("appid = #{record.appid,jdbcType=VARCHAR}");
        }
        
        if (record.getToken() != null) {
            SET("token = #{record.token,jdbcType=VARCHAR}");
        }
        
        if (record.getAeskey() != null) {
            SET("aeskey = #{record.aeskey,jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            SET("url = #{record.url,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtcreated() != null) {
            SET("gmtCreated = #{record.gmtcreated,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtmodified() != null) {
            SET("gmtModified = #{record.gmtmodified,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("wi_probe_open_third_info");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("appid = #{record.appid,jdbcType=VARCHAR}");
        SET("token = #{record.token,jdbcType=VARCHAR}");
        SET("aeskey = #{record.aeskey,jdbcType=VARCHAR}");
        SET("url = #{record.url,jdbcType=VARCHAR}");
        SET("gmtCreated = #{record.gmtcreated,jdbcType=TIMESTAMP}");
        SET("gmtModified = #{record.gmtmodified,jdbcType=TIMESTAMP}");
        
        OpenThirdInfoExample example = (OpenThirdInfoExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public String updateByPrimaryKeySelective(OpenThirdInfo record) {
        BEGIN();
        UPDATE("wi_probe_open_third_info");
        
        if (record.getAppid() != null) {
            SET("appid = #{appid,jdbcType=VARCHAR}");
        }
        
        if (record.getToken() != null) {
            SET("token = #{token,jdbcType=VARCHAR}");
        }
        
        if (record.getAeskey() != null) {
            SET("aeskey = #{aeskey,jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            SET("url = #{url,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtcreated() != null) {
            SET("gmtCreated = #{gmtcreated,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtmodified() != null) {
            SET("gmtModified = #{gmtmodified,jdbcType=TIMESTAMP}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_third_info
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    protected void applyWhere(OpenThirdInfoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}