package com.probe.open.entity;

import java.util.Date;

public class OpenThirdInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wi_probe_open_third_info.id
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wi_probe_open_third_info.appid
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wi_probe_open_third_info.token
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wi_probe_open_third_info.aeskey
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    private String aeskey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wi_probe_open_third_info.url
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wi_probe_open_third_info.gmtCreated
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    private Date gmtcreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wi_probe_open_third_info.gmtModified
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    private Date gmtmodified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wi_probe_open_third_info.id
     *
     * @return the value of wi_probe_open_third_info.id
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wi_probe_open_third_info.id
     *
     * @param id the value for wi_probe_open_third_info.id
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wi_probe_open_third_info.appid
     *
     * @return the value of wi_probe_open_third_info.appid
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wi_probe_open_third_info.appid
     *
     * @param appid the value for wi_probe_open_third_info.appid
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wi_probe_open_third_info.token
     *
     * @return the value of wi_probe_open_third_info.token
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wi_probe_open_third_info.token
     *
     * @param token the value for wi_probe_open_third_info.token
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wi_probe_open_third_info.aeskey
     *
     * @return the value of wi_probe_open_third_info.aeskey
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public String getAeskey() {
        return aeskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wi_probe_open_third_info.aeskey
     *
     * @param aeskey the value for wi_probe_open_third_info.aeskey
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public void setAeskey(String aeskey) {
        this.aeskey = aeskey == null ? null : aeskey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wi_probe_open_third_info.url
     *
     * @return the value of wi_probe_open_third_info.url
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wi_probe_open_third_info.url
     *
     * @param url the value for wi_probe_open_third_info.url
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wi_probe_open_third_info.gmtCreated
     *
     * @return the value of wi_probe_open_third_info.gmtCreated
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public Date getGmtcreated() {
        return gmtcreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wi_probe_open_third_info.gmtCreated
     *
     * @param gmtcreated the value for wi_probe_open_third_info.gmtCreated
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public void setGmtcreated(Date gmtcreated) {
        this.gmtcreated = gmtcreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wi_probe_open_third_info.gmtModified
     *
     * @return the value of wi_probe_open_third_info.gmtModified
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public Date getGmtmodified() {
        return gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wi_probe_open_third_info.gmtModified
     *
     * @param gmtmodified the value for wi_probe_open_third_info.gmtModified
     *
     * @mbggenerated Sun Nov 01 01:19:55 CST 2015
     */
    public void setGmtmodified(Date gmtmodified) {
        this.gmtmodified = gmtmodified;
    }
}