package com.probe.open.dao;

import com.probe.open.entity.PostRouter;
import com.probe.open.entity.PostRouterExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PostRouterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_post_router
     *
     * @mbggenerated Wed Nov 04 21:15:06 CST 2015
     */
    @SelectProvider(type=PostRouterSqlProvider.class, method="countByExample")
    int countByExample(PostRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_post_router
     *
     * @mbggenerated Wed Nov 04 21:15:06 CST 2015
     */
    @DeleteProvider(type=PostRouterSqlProvider.class, method="deleteByExample")
    int deleteByExample(PostRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_post_router
     *
     * @mbggenerated Wed Nov 04 21:15:06 CST 2015
     */
    @Delete({
        "delete from wi_probe_open_post_router",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_post_router
     *
     * @mbggenerated Wed Nov 04 21:15:06 CST 2015
     */
    @Insert({
        "insert into wi_probe_open_post_router (id, probeSn, ",
        "probeMac, thirdId, ",
        "gmtCreated, gmtModified)",
        "values (#{id,jdbcType=INTEGER}, #{probesn,jdbcType=VARCHAR}, ",
        "#{probemac,jdbcType=VARCHAR}, #{thirdid,jdbcType=INTEGER}, ",
        "#{gmtcreated,jdbcType=TIMESTAMP}, #{gmtmodified,jdbcType=TIMESTAMP})"
    })
    int insert(PostRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_post_router
     *
     * @mbggenerated Wed Nov 04 21:15:06 CST 2015
     */
    @InsertProvider(type=PostRouterSqlProvider.class, method="insertSelective")
    int insertSelective(PostRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_post_router
     *
     * @mbggenerated Wed Nov 04 21:15:06 CST 2015
     */
    @SelectProvider(type=PostRouterSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="probeSn", property="probesn", jdbcType=JdbcType.VARCHAR),
        @Result(column="probeMac", property="probemac", jdbcType=JdbcType.VARCHAR),
        @Result(column="thirdId", property="thirdid", jdbcType=JdbcType.INTEGER),
        @Result(column="gmtCreated", property="gmtcreated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmtModified", property="gmtmodified", jdbcType=JdbcType.TIMESTAMP)
    })
    List<PostRouter> selectByExample(PostRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_post_router
     *
     * @mbggenerated Wed Nov 04 21:15:06 CST 2015
     */
    @Select({
        "select",
        "id, probeSn, probeMac, thirdId, gmtCreated, gmtModified",
        "from wi_probe_open_post_router",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="probeSn", property="probesn", jdbcType=JdbcType.VARCHAR),
        @Result(column="probeMac", property="probemac", jdbcType=JdbcType.VARCHAR),
        @Result(column="thirdId", property="thirdid", jdbcType=JdbcType.INTEGER),
        @Result(column="gmtCreated", property="gmtcreated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmtModified", property="gmtmodified", jdbcType=JdbcType.TIMESTAMP)
    })
    PostRouter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_post_router
     *
     * @mbggenerated Wed Nov 04 21:15:06 CST 2015
     */
    @UpdateProvider(type=PostRouterSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PostRouter record, @Param("example") PostRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_post_router
     *
     * @mbggenerated Wed Nov 04 21:15:06 CST 2015
     */
    @UpdateProvider(type=PostRouterSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PostRouter record, @Param("example") PostRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_post_router
     *
     * @mbggenerated Wed Nov 04 21:15:06 CST 2015
     */
    @UpdateProvider(type=PostRouterSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PostRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wi_probe_open_post_router
     *
     * @mbggenerated Wed Nov 04 21:15:06 CST 2015
     */
    @Update({
        "update wi_probe_open_post_router",
        "set probeSn = #{probesn,jdbcType=VARCHAR},",
          "probeMac = #{probemac,jdbcType=VARCHAR},",
          "thirdId = #{thirdid,jdbcType=INTEGER},",
          "gmtCreated = #{gmtcreated,jdbcType=TIMESTAMP},",
          "gmtModified = #{gmtmodified,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PostRouter record);
}